resources:
- name: resource-test
  type: git
  source:
    uri: https://github.com/mcchow/CSS432_21W_The-Game.git
    branch: concourse-ci-setup
    username: joshua-sterner
    password: ((github-pw))

jobs:
- name: job-test-build
  public: true
  plan:
  - get: resource-test
    trigger: true
  - task: test-build
    file: resource-test/ci/task_test_build.yml
