resources:
- name: resource-repo
  type: git
  source:
    uri: https://github.com/mcchow/CSS432_21W_The-Game.git
    branch: dev
    username: joshua-sterner
    password: ((github-pw))

jobs:
- name: run-tests
  public: true
  plan:
  - get: resource-repo
    trigger: true
  - in_parallel:
    - task: run-client-tests
      file: resource-repo/ci/task_run_tests.yml
      vars:
        test_path: "resource-repo/TriviaGameClientTests"
    - task: run-server-tests
      file: resource-repo/ci/task_run_tests.yml
      vars:
        test_path: "resource-repo/TriviaGameServerTests"
